### ISSUE TITLE
As a user, I want to view on a map the correlation between a single Employment category and single Agricultural commodity, so that I can make a conclusion.

### ISSUE THREAD

**Issue by bmcelhaney** [swinkler149/901K-Sandbox#2]

**Comment by eahollin** [comment]
This is a dupe of AD002, right?  should this one be deleted since it has no number assigned?

**Comment by bmcelhaney** [comment]
I believe it is a dupe.  Should we remove?

**Comment by eahollin** [comment]
Yes

**Comment by eahollin** [comment]
The only thing I can see how to do is "Close".  don't see a delete button... :(
