### ISSUE TITLE
Duplicate Mongo Task?

### ISSUE THREAD

**Issue by tonypetruccelli** [swinkler149/901K-Sandbox#26]
Are Tasks 17  and 21 duplicates?  17 is "Acquire datasets and store in Mongo repository" and 21 is "Add data into our MongoDB" .  If so, i will delete the one I had added.  FYI -  I've been labeling these 'Tasks' until someone begins to work on one at which time they move it to 'Tasks-Dev', or at least that's how i understood the flow.

**Comment by eahollin** [comment]
I think "Acquire datasets and store in Mongo repository" may have originally been more like "Identify datasets..." or something like that, as right now, I don't see a task for simply finding the datasets in the first place, let alone what we do with them.  Thoughts on just renaming one of the tasks?

**Comment by SMIOP** [comment]
I thought we were labeling a task"Tasks Dev" or "Task Test" when the task is initially created rather than changing when a task is being worked on.

**Comment by tonypetruccelli** [comment]
ok I may have that wrong. What is the task label for then? Or did we just decide not to use that label?

Tony Petruccelli
INTEGRITYOne Partners
tony.petruccelli@ionep.com
703-581-6520

-------- Original message --------

**Comment by tonypetruccelli** [comment]
Bill said the links to the datasets are in his writeup. I'm fine with how you renamed them.  This one is perhaps a quick analysis of their structure and contents rather than the database implementation?

Tony Petruccelli
INTEGRITYOne Partners
tony.petruccelli@ionep.com
703-581-6520

-------- Original message --------

**Comment by eahollin** [comment]
Yes

**Comment by tonypetruccelli** [comment]
Issue resolved.  Closing issue.
