### ISSUE TITLE
More specifics on our user story needed

### ISSUE THREAD

**Issue by tonypetruccelli** [swinkler149/901K-Sandbox#33]
More details are needed from the product owner or the requirements analyst on what data is being used and how it is presented.  For example, within the Ag dataset, there are commodity product codes that further divide into other codes - should the dropdown expand to further refinement?  There are some codes that only provide data at the national level - how should the site respond? 

And what does a heat map of 2 attributes look like - are there colors that blend the 2 attributes?

**Comment by bmcelhaney** [comment]
To add more specifics and help with this User Story clarity, I have added a comment within [AD002](https://github.com/swinkler149/901K-Sandbox/issues/5).

**Comment by tonypetruccelli** [comment]
Issue closed.
