### ISSUE TITLE
Livereload.js timeout error

### ISSUE THREAD

**Issue by ferrx** [swinkler149/901K-Sandbox#43]
GET http://72.196.217.141:35729/livereload.js?snipver=1 net::ERR_CONNECTION_TIMED_OUT

This is causing slow loading (21s). Fast on local connection, but slow externally despite getting the same error.

I will look into this.

**Comment by ferrx** [comment]
This could be a port forwarding issue. Seems that livereload may need to have its own port? 

http://forum.codio.com/t/livereload-problems/735/3

Dead giveaway after noticing that the get request has a port of 35729 on it. I'll forward that port when I can to test this out.

**Comment by ferrx** [comment]
Bug SQUASHED.

Corrected LiveReload setup on server (by installing LiveReload on the server...), then forwarded VM and external ports, loads in 2-3s now instead of 20+ seconds.

**Comment by tonypetruccelli** [comment]
Like night and day!

Tony Petruccelli
INTEGRITYOne Partners
(w) 703-581-6520
(m) 703-629-0425
tony.petruccelli@ionep.commailto:tony.petruccelli@ionep.com
