### ISSUE TITLE
Usability - No State Selected confusing as default

### ISSUE THREAD

**Issue by tonypetruccelli** [swinkler149/901K-Sandbox#49]
Usability – ‘No State Selected’ comes up by default when the map first presents itself.  Somewhat confusing as you don’t select a state until after you use the filters.

**Comment by ferrx** [comment]
Fixed this by setting it to hidden until clicking the Correlate button.

Also I discovered that if you put #ID on a commit comment it will link to the corresponding issue, like this: #40 pretty cool. It also places a note in the issue that I made a reference to in the commit comment (see above this comment). +1 github
